"use client";
// Auto-generated by Spidey. Do not edit; this file is removed
// after generation completes.
import { StatCard as Spidey_Component } from "../../../components/StatCard";

const RAW_PROPS = {"label":"cupressus velut caelestis cruciamentum","value":"defessus","delta":35} as Record<string, unknown>;

function rehydrate(value: unknown): unknown {
  if (value === "__spidey_noop__") return () => {};
  if (Array.isArray(value)) return value.map(rehydrate);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = rehydrate(v);
    }
    return out;
  }
  return value;
}

export default function Page() {
  const props = rehydrate(RAW_PROPS) as Record<string, unknown>;
  return (
    <div
      style={{
        // Wrapper used by the capture step to measure the natural size of
        // the component preview. Its inline-block ensures the box hugs the
        // component instead of stretching to viewport width/height.
        display: "inline-block",
        padding: 16,
        background: "white",
      }}
      data-spidey-component-root="true"
    >
      {/* @ts-expect-error generated harness - any props */}
      <Spidey_Component {...props} />
    </div>
  );
}
